// <auto-generated />
using System;
using Book.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book.Api.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20230719151316_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book.Api.Context.DbRecords.BookingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af3a43af-0609-4ac0-a77a-652887c11bb7"),
                            EndDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            GuestName = "John Smith",
                            Guests = 2,
                            IsDeleted = false,
                            RoomId = new Guid("002f3b87-d57a-43d9-ba31-6531ebc6dbe3"),
                            StartDate = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("58641e5d-fb38-4df6-9df8-3e8c42fa2644"),
                            EndDate = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            GuestName = "Jane Doe",
                            Guests = 2,
                            IsDeleted = false,
                            RoomId = new Guid("002f3b87-d57a-43d9-ba31-6531ebc6dbe3"),
                            StartDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("94d4ccca-f9c5-46ae-ad48-61bb7ab4f899"),
                            EndDate = new DateTime(2023, 7, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            GuestName = "Peter McAllister",
                            Guests = 2,
                            IsDeleted = false,
                            RoomId = new Guid("002f3b87-d57a-43d9-ba31-6531ebc6dbe3"),
                            StartDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("a7ffdc04-0ba4-4607-9354-0ab0a1ce39e3"),
                            EndDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            GuestName = "Jane Austen",
                            Guests = 3,
                            IsDeleted = false,
                            RoomId = new Guid("1c591e3a-34af-4a46-84bb-3a39821dc930"),
                            StartDate = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("798b274a-b853-40df-9caf-c079f43fd29b"),
                            EndDate = new DateTime(2023, 7, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            GuestName = "Edgar Allan Poe",
                            Guests = 1,
                            IsDeleted = false,
                            RoomId = new Guid("1c591e3a-34af-4a46-84bb-3a39821dc930"),
                            StartDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("74260a32-8002-4dfa-850c-d9635e8a2f29"),
                            EndDate = new DateTime(2023, 7, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            GuestName = "Ernst Hemingway",
                            Guests = 2,
                            IsDeleted = false,
                            RoomId = new Guid("1c591e3a-34af-4a46-84bb-3a39821dc930"),
                            StartDate = new DateTime(2023, 7, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("5957ed91-41fc-48c0-ad8e-974713a75edb"),
                            EndDate = new DateTime(2023, 7, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            GuestName = "Humprey Bogart",
                            Guests = 2,
                            IsDeleted = false,
                            RoomId = new Guid("cc36d934-096b-4427-b759-e03630d190e8"),
                            StartDate = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("298880fe-9bb6-484e-93cb-ebc08efebf61"),
                            EndDate = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            GuestName = "Harrison Ford",
                            Guests = 4,
                            IsDeleted = false,
                            RoomId = new Guid("cc36d934-096b-4427-b759-e03630d190e8"),
                            StartDate = new DateTime(2023, 7, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("992aa3ae-3cf0-4ee7-91c1-420fc64ab9df"),
                            EndDate = new DateTime(2023, 8, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            GuestName = "Tom Hanks",
                            Guests = 2,
                            IsDeleted = false,
                            RoomId = new Guid("cc36d934-096b-4427-b759-e03630d190e8"),
                            StartDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Book.Api.Context.DbRecords.HotelRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("efe32237-1ccb-4c95-98de-8960bbfdf0be"),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Book.Api.Context.DbRecords.RoomRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("002f3b87-d57a-43d9-ba31-6531ebc6dbe3"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "101",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("9567a26c-d2dc-4149-97de-6d5de1a69ccb"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "102",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("4967c185-bd83-4fbd-ac87-a4e56edd3359"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "103",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ff557c7f-a9cd-498e-aab2-c16a7213651e"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "104",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e897ad97-170e-4dd7-9597-e8ea46f55344"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "105",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d17d7922-c4d7-4319-abaf-aea83aa724cc"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "106",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("cb17a359-4186-450c-8e7f-1387f8e2d155"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "107",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a78b8d99-e449-4bc4-a3d7-fa34dbd7185b"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "201",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("4780fec5-501e-49cf-9778-25310534a193"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "202",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("b7eba9d7-1ad9-4882-a793-80b3fa6548d8"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "203",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("bfc8c7f3-bc7f-4a71-8983-02f045400f09"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "204",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("8f606872-e733-48f8-bdeb-04d9bef751a9"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "205",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c1ca1a42-fb50-410f-ac40-f8b9dcae8e21"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "206",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("5a0828b0-fb3e-445f-b5f7-b542fe0b9b6f"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "302",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("392f8109-4616-4ca7-992c-faf01ba00762"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "303",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("229b6d7d-9482-447f-9501-546180da8a7f"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "304",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("fcf08489-96b9-4b2f-8eb0-c50ffe8bf4ee"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "305",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a1b43a9a-a88e-4258-a572-5498e0fb3259"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "306",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c947c771-17f6-41ae-b8c0-70edb5213d04"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "401",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("e7fcea98-cc16-4581-9747-d48316aea3fe"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "402",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("16c37356-eb57-4c0e-a767-396d73bc7a49"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "403",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("12473933-3a14-4858-954f-7fd0e8402c84"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "404",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("32a9d0c1-d129-425e-bcb9-54df52d042c9"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "501",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("dbdcb678-0c6f-4ecd-90ad-ec899ebca496"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "502",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("3456e524-1f22-4c80-ab6c-ae386de9b3ff"),
                            HotelId = new Guid("086f2dae-aac0-4de4-9ad1-64662759430a"),
                            IsDeleted = false,
                            Name = "503",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("95d8e017-feb4-4b8d-831a-b57389b40f67"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "1001",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("6d2e4603-b909-4dc8-ae32-5e46f0cb9ffb"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "1002",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("30e4b36f-a380-407b-92d9-ad5fb6a68a27"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "1003",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b6d9c9fa-944f-4aec-89ca-95b544b82cfc"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "1004",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("ac7b2754-ed2b-46c9-b265-9f02746e01a4"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "2001",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("444c1cb8-83f7-4ae2-9e35-78166517e118"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "2002",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("725e607d-93b1-4dbd-943f-79f8243e8de4"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "2003",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("741c5263-60e0-4349-8821-c1cd9046a789"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "2004",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("fc2c89e1-822b-4709-bb2f-d39e9044e69e"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "2005",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("225d6dcc-546d-441c-b695-393b641f1bea"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "2006",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("e23c12b6-86a4-49aa-bf2d-6da3c9854aeb"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "3001",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("1c591e3a-34af-4a46-84bb-3a39821dc930"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "3002",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("53cb40b7-b454-4473-876c-ac76c6f75038"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "3003",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("6a9c49d5-6349-45d6-b2f7-2a22cacebed0"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "3004",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("5def7269-45e6-45a8-8949-2486115df694"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "3005",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ca69ff46-9e8e-483d-bbfe-071e38166502"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "3006",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c41d6c60-5e20-49d1-b778-6ae1780c3450"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "4001",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7204d838-1bb2-4893-8cbf-9d7eb4c99d00"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "4002",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b116361e-c0da-4000-bad0-eebe986b3b44"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "4003",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("d9a3fc35-c2fa-461c-9be9-5d41f86ee4a2"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "5001",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("9cdcda25-4b79-4f31-b09e-43adfc89943b"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "5002",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("ec1f612e-80d1-40f6-8a63-a64faed918ff"),
                            HotelId = new Guid("08f6372e-b332-412a-bb61-a5d9682bc9a7"),
                            IsDeleted = false,
                            Name = "5003",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("cc36d934-096b-4427-b759-e03630d190e8"),
                            HotelId = new Guid("efe32237-1ccb-4c95-98de-8960bbfdf0be"),
                            IsDeleted = false,
                            Name = "A",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("21df563d-7157-4707-80f0-a725794bf76b"),
                            HotelId = new Guid("efe32237-1ccb-4c95-98de-8960bbfdf0be"),
                            IsDeleted = false,
                            Name = "B",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("cf842faf-beef-4a2a-aa5d-d634830a0de3"),
                            HotelId = new Guid("efe32237-1ccb-4c95-98de-8960bbfdf0be"),
                            IsDeleted = false,
                            Name = "C",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("faeb8c43-1b1b-41b4-a7e1-e0e79bd54fb0"),
                            HotelId = new Guid("efe32237-1ccb-4c95-98de-8960bbfdf0be"),
                            IsDeleted = false,
                            Name = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("86f78365-5bd4-4084-9c01-ba4ce4be93b1"),
                            HotelId = new Guid("efe32237-1ccb-4c95-98de-8960bbfdf0be"),
                            IsDeleted = false,
                            Name = "E",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("12cdb371-f079-4a86-9686-f13d8215a571"),
                            HotelId = new Guid("efe32237-1ccb-4c95-98de-8960bbfdf0be"),
                            IsDeleted = false,
                            Name = "F",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Book.Api.Context.DbRecords.BookingRecord", b =>
                {
                    b.HasOne("Book.Api.Context.DbRecords.RoomRecord", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Book.Api.Context.DbRecords.RoomRecord", b =>
                {
                    b.HasOne("Book.Api.Context.DbRecords.HotelRecord", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Book.Api.Context.DbRecords.HotelRecord", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Book.Api.Context.DbRecords.RoomRecord", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
